Repository Axelrod-Python/Axelrod, pull requests merged in 2018-08, with the labels that each got.

#1189 Fix bug where add_loops assumes that edges are enumerated integers
  axelrod/graph.py
  axelrod/tests/unit/test_graph.py
  axelrod/tests/unit/test_moran.py
Labels: bug

#1188 Add a page of citations
  citations.md
Labels: ready-to-merge

#1190 Modify/fix initial play of lookerup players.
  axelrod/strategies/lookerup.py
  axelrod/tests/strategies/test_geller.py
Labels: bug, ready-to-merge

#1191 Fix Inconsistant CI failures
  axelrod/tests/unit/test_plot.py
  doctests.py
Labels: bug, ready-to-merge

#1195 Spruce up deterministic_cache
  axelrod/deterministic_cache.py
  axelrod/tests/unit/test_deterministic_cache.py
Labels: ready-to-merge

#1194 Add a matplotlibrc
  axelrod/tests/unit/test_fingerprint.py
  axelrod/tests/unit/test_moran.py
  axelrod/tests/unit/test_plot.py
  doctests.py
  matplotlibrc
Labels: ready-to-merge

#1204 Unpin sphinx on travis.
  .travis.yml
Labels: ready-to-merge
