Repository Axelrod-Python/Axelrod, pull requests merged in 2020-04, with the labels that each got.

#1305 Fix ResultSet __eq__ to handle nans
  axelrod/result_set.py
  axelrod/tests/unit/test_eigen.py
  axelrod/tests/unit/test_resultset.py
Labels: ready-to-merge

#1300 Move classifiers outside of Players
  axelrod/__init__.py
  axelrod/classifier.py
  axelrod/data/all_classifiers.yml
  axelrod/deterministic_cache.py
  axelrod/match.py
  axelrod/player.py
  axelrod/strategies/__init__.py
  axelrod/strategies/_filters.py
  axelrod/strategies/meta.py
  axelrod/tests/integration/test_filtering.py
  axelrod/tests/integration/test_matches.py
  axelrod/tests/integration/test_sample_tournaments.py
  axelrod/tests/integration/test_tournament.py
  axelrod/tests/strategies/test_cycler.py
  axelrod/tests/strategies/test_hmm.py
  axelrod/tests/strategies/test_lookerup.py
  axelrod/tests/strategies/test_memoryone.py
  axelrod/tests/strategies/test_memorytwo.py
  axelrod/tests/strategies/test_meta.py
  axelrod/tests/strategies/test_player.py
  axelrod/tests/strategies/test_rand.py
  axelrod/tests/strategies/test_titfortat.py
  axelrod/tests/unit/test_classification.py
  axelrod/tests/unit/test_filters.py
  axelrod/tests/unit/test_property.py
  axelrod/tests/unit/test_strategy_transformers.py
  axelrod/tests/unit/test_tournament.py
  docs/tutorials/advanced/classification_of_strategies.rst
  docs/tutorials/contributing/strategy/adding_the_new_strategy.rst
  docs/tutorials/contributing/strategy/classifying_the_new_strategy.rst
  rebuild_classifier_table.py
  requirements.txt
Labels: ready-for-review

#1307 Create function to handle relative paths
  axelrod/load_data_.py
  axelrod/plot.py
  axelrod/tests/integration/test_tournament.py
  axelrod/tests/unit/test_deterministic_cache.py
  axelrod/tests/unit/test_fingerprint.py
  axelrod/tests/unit/test_load_data.py
  axelrod/tests/unit/test_plot.py
  axelrod/tests/unit/test_resultset.py
  axelrod/tests/unit/test_tournament.py
  requirements.txt
Labels: ready-to-merge

#1313 Mock yaml in documentation for rtd
  docs/conf.py
Labels: bug

#1314 Fix broken data file imports.
  MANIFEST.in
  setup.py
Labels: bug

#1310 Add Wang et al to citations.
  citations.md
Labels: ready-to-merge

#1318 Update core contributors list.
  README.rst
Labels: ready-to-merge

#1321 Update the nbr of strategies in first page of docs
  docs/index.rst
Labels: ready-to-merge

#1322 Add weekly CI run.
  .github/workflows/config.yml
Labels: ready-to-merge

#1323 Fix RevisedDowning
  axelrod/strategies/revised_downing.py
  axelrod/tests/strategies/test_revised_downing.py
Labels: ready-to-merge

#1329 Add documentation about hypothesis
  docs/tutorials/contributing/running_tests.rst
Labels: ready-to-merge
